services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-leds
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=db-leds;User=root;Password=root;
    ports:
      - "8080:8080"
    command: ["sh", "-c", "dotnet ef database update && dotnet TrilhaBackendLeds.dll"]

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-leds
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: