services: 
  sqlserver: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Leds2025@Dev"
      ACCEPT_EULA: "Y"
    networks:
      - app_network
  api:
    build:
      context: ./VenhaParaOLEDS
    container_name: venha_api
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./dados:/app/dados
    networks:
      - app_network


networks:
  app_network:
    driver: bridge