// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrilhaBackendLeds.Context;

#nullable disable

namespace TrilhaBackendLeds.Migrations
{
    [DbContext(typeof(TrilhaBackEndLedsContext))]
    [Migration("20250226181158_PopulateConcursos")]
    partial class PopulateConcursos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TrilhaBackendLeds.Models.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateOnly>("DataDeNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("TrilhaBackendLeds.Models.CandidatoProfissao", b =>
                {
                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<int>("ProfissaoId")
                        .HasColumnType("int");

                    b.HasKey("CandidatoId", "ProfissaoId");

                    b.HasIndex("ProfissaoId");

                    b.ToTable("candidato_profissao");
                });

            modelBuilder.Entity("TrilhaBackendLeds.Models.Concurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoDoConcurso")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id");

                    b.ToTable("Concursos");
                });

            modelBuilder.Entity("TrilhaBackendLeds.Models.Edital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConcursoId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroDoEdital")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("OrgaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConcursoId");

                    b.HasIndex("OrgaoId");

                    b.ToTable("Editais");
                });

            modelBuilder.Entity("TrilhaBackendLeds.Models.Orgao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Orgaos");
                });

            modelBuilder.Entity("TrilhaBackendLeds.Models.Profissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Profissoes");
                });

            modelBuilder.Entity("TrilhaBackendLeds.Models.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("editalId")
                        .HasColumnType("int");

                    b.Property<int?>("profissaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("editalId");

                    b.HasIndex("profissaoId");

                    b.ToTable("Vagas");
                });

            modelBuilder.Entity("TrilhaBackendLeds.Models.CandidatoProfissao", b =>
                {
                    b.HasOne("TrilhaBackendLeds.Models.Candidato", "Candidato")
                        .WithMany("CandidatoProfissoes")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrilhaBackendLeds.Models.Profissao", "Profissao")
                        .WithMany("CandidatoProfissoes")
                        .HasForeignKey("ProfissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Profissao");
                });

            modelBuilder.Entity("TrilhaBackendLeds.Models.Edital", b =>
                {
                    b.HasOne("TrilhaBackendLeds.Models.Concurso", "Concurso")
                        .WithMany("Editais")
                        .HasForeignKey("ConcursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrilhaBackendLeds.Models.Orgao", "Orgao")
                        .WithMany("Editais")
                        .HasForeignKey("OrgaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concurso");

                    b.Navigation("Orgao");
                });

            modelBuilder.Entity("TrilhaBackendLeds.Models.Vaga", b =>
                {
                    b.HasOne("TrilhaBackendLeds.Models.Edital", "edital")
                        .WithMany("Vagas")
                        .HasForeignKey("editalId");

                    b.HasOne("TrilhaBackendLeds.Models.Profissao", "profissao")
                        .WithMany("Vagas")
                        .HasForeignKey("profissaoId");

                    b.Navigation("edital");

                    b.Navigation("profissao");
                });

            modelBuilder.Entity("TrilhaBackendLeds.Models.Candidato", b =>
                {
                    b.Navigation("CandidatoProfissoes");
                });

            modelBuilder.Entity("TrilhaBackendLeds.Models.Concurso", b =>
                {
                    b.Navigation("Editais");
                });

            modelBuilder.Entity("TrilhaBackendLeds.Models.Edital", b =>
                {
                    b.Navigation("Vagas");
                });

            modelBuilder.Entity("TrilhaBackendLeds.Models.Orgao", b =>
                {
                    b.Navigation("Editais");
                });

            modelBuilder.Entity("TrilhaBackendLeds.Models.Profissao", b =>
                {
                    b.Navigation("CandidatoProfissoes");

                    b.Navigation("Vagas");
                });
#pragma warning restore 612, 618
        }
    }
}
